services:
  app:
    container_name: project_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python -m app.main'
    volumes:
      - ./app:/src/app
    ports:
      - $8000:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: project_postgres
    image: postgres:16.3
    environment:
      - POSTGRES_DB=edu_platform_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    restart: always