services:
  app:
    container_name: project_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python -m app.main'
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always